### ISSUE TITLE
Pass Runner Guidelines

### ISSUE THREAD

**Issue by ai** [theprotein/enb-postcss#1]
PostCSS has [Guidelines for Runners](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md) like this one. On quick look I found this problems:
- [x] 2.1. Set `from` and `to` processing options
- [x] 2.2. Use only the asynchronous API
- [x] 3.1. Don’t show JS stack for `CssSyntaxError`
- [x] 3.2. Display `result.warnings()`
- [x] 4.2. Maintain a changelog
- [x] 4.3. `postcss-runner` keyword in `package.json`

Also, does ENB supports source map?

What `enb-autoprefixer` team thinks? @isqua @mdevils @blond

/cc @verybigman

**Comment by awinogradov** [comment]
@ai I do this all! And source maps to)

**Comment by ai** [comment]
@verybigman awesome. Ask me any questions in PostCSS’s Gitter.

**Comment by awinogradov** [comment]
Ok, men!)

**Comment by awinogradov** [comment]
All done! 6b79de948a

**Comment by isqua** [comment]
Yesterday I wondered to write enb-postcss. Perfect.
:+1:
