### ISSUE TITLE
Add "source" option

### ISSUE THREAD

**Issue by 4ok** [theprotein/enb-postcss#13]
I would like to use this technology after another. For example after "stylus".

**Comment by awinogradov** [comment]
https://github.com/bem-incubator/bem-grid/blob/master/.enb/make.js#L27

**Comment by 4ok** [comment]
I don't see the option "source" https://github.com/awinogradov/enb-postcss/blob/master/techs/enb-postcss.js#L10-L12, but see only "useFileList" https://github.com/awinogradov/enb-postcss/blob/master/techs/enb-postcss.js#L13.

Now i use this module — https://github.com/tadatuta/enb-bundle-postcss
