### ISSUE TITLE
Add "source" option. Based on "issues/13"

### ISSUE THREAD

**Issue by 4ok** [theprotein/enb-postcss#14]
https://github.com/awinogradov/enb-postcss/issues/13#issuecomment-174727962

**Comment by awinogradov** [comment]
@4ok You can add this code `.useSourceFilename('source', '?.post.css')` to the tech definition of `enb-postcss` and make PR. I'll be happy to merge it and make new patch version ;)

**Comment by 4ok** [comment]
:ok_hand:

**Comment by adinvadim** [comment]
@awinogradov if add this code it's all, then i've done
https://github.com/awinogradov/enb-postcss/pull/18
