### ISSUE TITLE
Add option for postcss import plugin

### ISSUE THREAD

**Issue by adinvadim** [theprotein/enb-postcss#22]
In enb-postcss is used postcss-import, but there are some cases, when user need other one.
For example:
precss use postcss-partial-import
Now, sugarSS correct work only with postcss-easy-import

To not break backward compatibility enb-postcss will use by default postcss-import

@awinogradov Any suggestions or objection?

**Comment by awinogradov** [comment]
We can remove postcss-import from core. You can add postcss-import with others plugins and custom props.

**Comment by adinvadim** [comment]
https://github.com/awinogradov/enb-postcss/pull/24
