### ISSUE TITLE
Move to enb organization

### ISSUE THREAD

**Issue by blond** [theprotein/enb-postcss#28]
![common](http://33.media.tumblr.com/9fde836a1286d261b60e414bbdb88d6a/tumblr_inline_n9whoaxOB41rqc8us.gif)

**Comment by awinogradov** [comment]
😺 Why?

**Comment by blond** [comment]
why not? )

**Comment by awinogradov** [comment]
@blond Any benefits?)

**Comment by blond** [comment]
- Users more easily find the package.
- Our infrastructure will have the right to pack.

**Comment by awinogradov** [comment]
>  right to pack.

![tupac](http://i.giphy.com/E2uKqBQURFHfG.gif)

**Comment by awinogradov** [comment]
It's not necessary
